### ISSUE TITLE
A error [LiDARTag/lidar_tag-3] process has died [pid 28260, exit code -11

### ISSUE THREAD

**Issue by plumewind** [UMich-BipedLab/automatic_lidar_camera_calibration#2]
hello,

This is a great tool! I want to use it in my own lidar-camera system, but I encountered a serious error when testing your dataset.

My ubuntu is 18.04 version, the log file is as follows, using your train / extrinsic_train9.bag

[master.log](https://github.com/UMich-BipedLab/automatic_lidar_camera_calibration/files/4414640/master.log)

Can you help me? Thanks a lot~

**Comment by plumewind** [comment]
hello,

I use my data to test system, but got another paoblem:

=========================== 
=========================== 
[ INFO] [1585740690.667098068]: ALL INITIALIZED!
[ INFO] [1585740690.673360449]: Waiting for pointcloud data
[ INFO] [1585740722.382202991]: Got pointcloud data
[ INFO] [1585740722.382265098]: Analyzing system
[ INFO] [1585740722.382993150]: ...Finished waiting for IMAGE!!
Creating apriltag_detector...
Starting the APRILTAG LOOP
-->creating tag16h5 family
-->created tag16h5 family
Failed to find match for field 'ring'.
Failed to find match for field 'ring'.
Failed to find match for field 'ring'.
Failed to find match for field 'ring'.
Failed to find match for field 'ring'.

Do you know the reason? Thanks

**Comment by brucejk** [comment]
Hi, 

First, I have to apologize that the repo has been really well documented (I am still working on it) and I am glad that you would like to give it a try. I will definitely try my best to help you!

Second, please pull again from the [_LiDARTag_](https://github.com/UMich-BipedLab/LiDARTag) package.

Third, to your first question, I am assuming that you have successfully built the following package:
    1. [_sync_lidartag_apriltag_](https://github.com/UMich-BipedLab/sync_lidartag_apriltag),
    2. [_alignment_msgs_](https://github.com/UMich-BipedLab/alignment_msgs),
    3. [_LiDARTag_](https://github.com/UMich-BipedLab/LiDARTag),
    4. [_LiDARTag_msgs_](https://github.com/UMich-BipedLab/LiDARTag_msgs),
    5. [_AprilTag_ROS_](https://github.com/UMich-BipedLab/AprilTag_ROS),
    6. [_AprilTag_msgs_](https://github.com/UMich-BipedLab/AprilTag_msgs).
After you pull from the [_LiDARTag_](https://github.com/UMich-BipedLab/LiDARTag), please run again to see if you still have the same problem.

Last, could you tell me which LiDAR you do you use? It seems like your sensor does not have ring numbers. The problem would be more clear if you can directly run the [_LiDARTag_](https://github.com/UMich-BipedLab/LiDARTag) to see what the output is.

**Comment by plumewind** [comment]
hello, 

First of all, there is a problem with my dataset. It does not have ring numbers, so I want to run with your dataset first.

 Now， I will pull your pkg again, compile and try ......

**Comment by plumewind** [comment]
By the way , I find a mistake :

in sync_lidartag_apriltag/launch/sync_cam_lidar.launch:
in the end , should it like this??

    <node pkg="apriltag3ROS" name="apriltag3ROS" type="apriltag3_pub" output="screen">
        <param name="image_topic" type="string" value="$(arg synced_image_topic)" />
        <param name="detection_topic" type="string" value="/apriltag2ROS/apriltag2_tag_detection" />
        <param name="detection_array_topic" type="string" value="/apriltag2ROS/apriltag2_tag_detections_array" /> 
        <param name="blur_percent" type="string" value ="0.0" />
        
    </node>

Because what you generate is this， from AprilTag_ROS/CMakeLists.txt ,  Is that right?
 Or appears:
process[LiDARTag/lidar_tag-3]: started with pid [21250]
ERROR: cannot launch node of type [apriltag2ROS/apriltag2_pub]: apriltag2ROS
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/home/bran/catkin_tagcalib2/src
ROS path [2]=/home/bran/catkin_tagcalib/src
ROS path [3]=/opt/ros/melodic/share

**Comment by plumewind** [comment]
hello,
 
The system goes well on your data, but the view-windows is alway black, is that OK?

and in the end, ctrl +C to end rosnode, but it appears:

Lidartag target depth: 13.6328
Lidartag target depth: 13.6167
^C[apriltag3ROS-4] killing on exit
[LiDARTag/lidar_tag-3] killing on exit
[sync_cam_lidar-2] killing on exit
Done!
[apriltag3ROS-4] escalating to SIGTERM
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done


and in the output file, I only see two file no mat file, is that OK?

**Comment by brucejk** [comment]
Oh, I fixed on my end but didn't push. I just pushed. Thanks for the reminder!

**Comment by brucejk** [comment]
1. Oh, I fixed on my end but didn't push. I just pushed. Thanks for the reminder! 
2. Do you mean the view-window from the AprilTag package? It should have something like this:
![image](https://user-images.githubusercontent.com/26856926/78283068-44491c00-74eb-11ea-9337-c46cf43cbc85.png)
3. You will have to record bagfiles on your path, and save them to your favorite folder! 
4. This repo will directly read all the bagfiles you have saved in the folder and then proceed! Also, remember to change the [path.bag_file_path](https://github.com/UMich-BipedLab/automatic_lidar_camera_calibration/blob/e74382f4283576702a271fdbfe526b48c0c1acdb/automatic_calibration_main.m#L105) in [_automatic_calibration_main.m](https://github.com/UMich-BipedLab/automatic_lidar_camera_calibration/blob/release_v1/automatic_calibration_main.m)_ and run. Please read [here](https://github.com/UMich-BipedLab/automatic_lidar_camera_calibration/blob/release_v1/README.md#running). 

Please let me know if you encounter any other issues!

**Comment by plumewind** [comment]
hello, is it a mistake?

Sorry, I found and solved it a few days ago, but forgot to tell you.

`apriltag3_ros.cpp: In member function ‘void apriltag3_detector_ros::Node::spin(int, char**)’:
/home/bran/catkin_tagcalib/src/AprilTag_ROS/src/apriltag3_ros.cpp:413:9: error: ‘getopt_t’ was not declared in this scope
         getopt_t *getopt = getopt_create();`

in  AprilTag_ROS/src/apriltag3_ros.cpp,  add:

`#include "getopt.h"
#include  <unistd.h>`

**Comment by brucejk** [comment]
Thanks for the feedback! I didn't encounter this error but I added them. I also made some small changes in the AprilTag_ros repo. Please pull it again.

**Comment by mac137** [comment]
Hi! 

> Hi,
> 
> First, I have to apologize that the repo has been really well documented (I am still working on it) and I am glad that you would like to give it a try. I will definitely try my best to help you!
> 
> Second, please pull again from the [_LiDARTag_](https://github.com/UMich-BipedLab/LiDARTag) package.
> 
> Third, to your first question, I am assuming that you have successfully built the following package:
> 1. [_sync_lidartag_apriltag_](https://github.com/UMich-BipedLab/sync_lidartag_apriltag),
> 2. [_alignment_msgs_](https://github.com/UMich-BipedLab/alignment_msgs),
> 3. [_LiDARTag_](https://github.com/UMich-BipedLab/LiDARTag),
> 4. [_LiDARTag_msgs_](https://github.com/UMich-BipedLab/LiDARTag_msgs),
> 5. [_AprilTag_ROS_](https://github.com/UMich-BipedLab/AprilTag_ROS),
> 6. [_AprilTag_msgs_](https://github.com/UMich-BipedLab/AprilTag_msgs).
> After you pull from the [_LiDARTag_](https://github.com/UMich-BipedLab/LiDARTag), please run again to see if you still have the same problem.
> 
> Last, could you tell me which LiDAR you do you use? It seems like your sensor does not have ring numbers. The problem would be more clear if you can directly run the [_LiDARTag_](https://github.com/UMich-BipedLab/LiDARTag) to see what the output is.

I cannot build the AprilTag_ROS package and posted an issue in that repository:
https://github.com/UMich-BipedLab/AprilTag_ROS/issues/1#issue-593961211

**Comment by plumewind** [comment]
OK , it is cool !
