### ISSUE TITLE
topics to record for "backend"

### ISSUE THREAD

**Issue by mac137** [UMich-BipedLab/automatic_lidar_camera_calibration#3]
Hi! I have played the video and lidar data and launched these:
```
roslaunch sync_cam_lidar sync_cam_lidar.launch
roslaunch sync_cam_lidar alignment_node_only.launch
```
the list of topics is as follows:
```
/LiDARTag/lidar_tag/BoundaryMarker
/LiDARTag/lidar_tag/ClusterMarker
/LiDARTag/lidar_tag/ClusterPC
/LiDARTag/lidar_tag/DetectedPC
/LiDARTag/lidar_tag/EdgedPC
/LiDARTag/lidar_tag/Grid
/LiDARTag/lidar_tag/GridLine
/LiDARTag/lidar_tag/LiDARTagDetectionArray
/LiDARTag/lidar_tag/LiDARTagPose
/LiDARTag/lidar_tag/Payload
/LiDARTag/lidar_tag/PayloadEdges
/apriltag2ROS/apriltag2_tag_detections_array
/camera/color/camera_info
/camera/color/image_raw
/clicked_point
/clock
/initialpose
/move_base_simple/goal
/rosout
/rosout_agg
/sync_cam_lidar/image_sync
/sync_cam_lidar/velodyne_points_sync
/tf
/tf_static
/velodyne_nodelet_manager/bond
/velodyne_nodelet_manager_cloud/parameter_descriptions
/velodyne_nodelet_manager_cloud/parameter_updates
/velodyne_nodelet_manager_driver/parameter_descriptions
/velodyne_nodelet_manager_driver/parameter_updates
/velodyne_nodelet_manager_laserscan/parameter_descriptions
/velodyne_nodelet_manager_laserscan/parameter_updates
/velodyne_packets
/velodyne_points
```
should I record these two as an input to the backend?
```
/LiDARTag/lidar_tag/LiDARTagDetectionArray
/apriltag2ROS/apriltag2_tag_detections_array
```
I am asking because when I echo the latter, nothing seems to appear:
`maciej@CIT-MACIEJ-U:~/ros/umich-calibration$ rostopic echo apriltag2ROS/apriltag2_tag_detections_array`
```
maciej@CIT-MACIEJ-U:~/ros/umich-calibration$ rostopic info apriltag2ROS/apriltag2_tag_detections_array
Type: apriltag_msgs/AprilTagDetectionArray

Publishers: None

Subscribers: 
 * /detection_align_node (http://CIT-MACIEJ-U:41005/)
```
What should be the output? how to check if that is correct input to the "backend"?

**Comment by plumewind** [comment]
hello,

I also have this problem, which topics should I record?

**Comment by plumewind** [comment]
Look the bag2mat.py, this:

 `if len(sys.argv)==1:
            bag_name = "bagfile.bag" 
            event_name = "event-name"
            read_topic1 = "/LiDARTag"
            read_topic2 = "/LiDARTag/DetectedPC"
            read_topic3 = "/rslidar_points"
        elif len(sys.argv)==2:
            bag_name = sys.argv[1]
            event_name = "event-name"
            read_topic1 = "/LiDARTag"
            read_topic2 = "/LiDARTag/DetectedPC"
            read_topic3 = "/rslidar_points"
        elif len(sys.argv)==3:
            bag_name = sys.argv[1]
            event_name = sys.argv[2]
            read_topic1 = "/LiDARTag"
            read_topic2 = "/LiDARTag/DetectedPC"
            read_topic3 = "/rslidar_points"
        elif len(sys.argv)==4:
            bag_name = sys.argv[1]
            event_name = sys.argv[2]
            read_topic1 = sys.argv[3]
            read_topic2 = "/LiDARTag/DetectedPC"
            read_topic3 = "/rslidar_points"
        else:
            print("wrong number of arguments")
            sys.exit();

        topics = [read_topic1, read_topic2, read_topic3]
        topics = [read_topic3]
        bagfile = path + bag_name 
        print 'Loading rosbag: ', bagfile
        print 'Topics are: ', topics

        convertToMatFile(bagfile, topics, event_name, extracted)
`

Is that say, topics are  
`           
 read_topic1 = "/LiDARTag"
 read_topic2 = "/LiDARTag/DetectedPC"
 read_topic3 = "/rslidar_points"
` 
??

**Comment by brucejk** [comment]
Hi all, 

I am still working on this. I will revise this comment in a bit. Sorry it takes a little bit longer than I thought! I will get back to you guys as soon as possible. I am trying to make it easier to use.

**Comment by plumewind** [comment]
cool ,thanks.

more quickly, more well.

**Comment by brucejk** [comment]
Hi all, 

Sorry for the delay. I have updated the following package, 
    - [_sync_lidartag_apriltag_](https://github.com/UMich-BipedLab/sync_lidartag_apriltag),
    - [_LiDARTag_](https://github.com/UMich-BipedLab/LiDARTag),
    - [_AprilTag_ROS_](https://github.com/UMich-BipedLab/AprilTag_ROS),
please pull again. 

All you need to do now is run [cam_lidar_front_end3.launch](https://github.com/UMich-BipedLab/sync_lidartag_apriltag/blob/release/launch/cam_lidar_front_end3.launch) if you are using AprilTag3 (run [cam_lidar_front_end2.launch](https://github.com/UMich-BipedLab/sync_lidartag_apriltag/blob/release/launch/cam_lidar_front_end2.launch) if you are using AprilTag2), and record the _/detection_align/tag_alignment_ topic.
