### ISSUE TITLE
ground truth rotation and translation parameters

### ISSUE THREAD

**Issue by xmba15** [UMich-BipedLab/automatic_lidar_camera_calibration#4]
Hi, @brucejk Thank you very much for making the whole project open-source.
Can you please also share the transformation parameters for the lidar-camera set in the https://github.com/UMich-BipedLab/automatic_lidar_camera_calibration#dataset?

Currently, I cannot gather the whole Matlab environment with me to run the whole code to get the result.

**Comment by brucejk** [comment]
Hi, 

Thanks for using our software! 

We do not have ground truth rotation and translation for our LiDAR-camera pair. We only use parameters from the CAD models. 

Please let me know if you encounter any other questions/issues.

**Comment by xmba15** [comment]
Thanks for the reply @brucejk 
Can you please share the parameters from the CAD models if you still keep it?
If possible, I would like to know the two tag sizes (both left and right apriltags) defined by the blue arrow in the following picture. (I think the tag size you used in the source code also considers the white border area).
![apriltag](https://user-images.githubusercontent.com/18694765/148080006-d29bed5c-d021-46ef-b503-2262403e3b4d.png)
Thank you in advance.

**Comment by brucejk** [comment]
Hi, 

1. The parameters should be the same as: https://github.com/UMich-BipedLab/extrinsic_lidar_camera_calibration/blob/d423c81e95c6de595e1dff79871385348b1c68f4/justCalibrate.m#L33
2. The length (x cm) in the code is eight bits. If you want to just have the length for the black (six bits), please do (x / 8) * 6. This should give you the length of the blue arrow. 

Please let me know if you have other questions!

**Comment by xmba15** [comment]
Thank you very much for the information  @brucejk
